[jamstac]
    [jamstac.assets]
        [jamstac.assets.styles]
            head = [ "base" ]
            foot = [ "base" ]
        [jamstac.assets.script]
            head = [ "main" ]
            foot = [ "main" ]

